// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnODOFlDXUhjhlmA9OlB0anAtJN2S09Zs',
    appId: '1:280047957230:web:5dea65d79f7dfa587dafff',
    messagingSenderId: '280047957230',
    projectId: 'login-signup-flutter-project',
    authDomain: 'login-signup-flutter-project.firebaseapp.com',
    storageBucket: 'login-signup-flutter-project.firebasestorage.app',
    measurementId: 'G-T46TN7Q34H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4LysmNQy6z5gT0hLUvQ5tGXaBbSRh2c8',
    appId: '1:280047957230:android:fa86c5a429a5ed0b7dafff',
    messagingSenderId: '280047957230',
    projectId: 'login-signup-flutter-project',
    storageBucket: 'login-signup-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9sFlsXJvqn0kUxKsAuhM7aOJ1kFgf_GE',
    appId: '1:280047957230:ios:43f4391ddea4488b7dafff',
    messagingSenderId: '280047957230',
    projectId: 'login-signup-flutter-project',
    storageBucket: 'login-signup-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9sFlsXJvqn0kUxKsAuhM7aOJ1kFgf_GE',
    appId: '1:280047957230:ios:43f4391ddea4488b7dafff',
    messagingSenderId: '280047957230',
    projectId: 'login-signup-flutter-project',
    storageBucket: 'login-signup-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnODOFlDXUhjhlmA9OlB0anAtJN2S09Zs',
    appId: '1:280047957230:web:6f9a0b90803e44b97dafff',
    messagingSenderId: '280047957230',
    projectId: 'login-signup-flutter-project',
    authDomain: 'login-signup-flutter-project.firebaseapp.com',
    storageBucket: 'login-signup-flutter-project.firebasestorage.app',
    measurementId: 'G-P2Q1XQN25R',
  );
}
